### ISSUE TITLE
Cleanup all temporary workarounds

### ISSUE THREAD

**Issue by TheMrMilchmann** [TheMrMilchmann/Osmerion#15]
In order to ensure that the project can be build with Gradle on JDK9 several workarounds have been introduced to the build scripts. This issues is used to keep track of the temporary hacks that need to be removed as soon as possible.

This requires Gradle to support building Jigsaw modules.

- [ ] Ensure that Gradle builds the modules without modifying the `javaCompile` task.
- [ ] Ensure that the Kotlin compilation and execution succeeds on JDK9.
- [ ] Ensure that Gradle Kotlin runs on the same JDK9 version that is used to compile the modules.

**Comment by TheMrMilchmann** [comment]
Blocked by #18.
